### PR TITLE
Add native image build

### PR DESCRIPTION
**Pull request by npepinpe**
This PR adds a maven profile which builds a native image of the `cli` distribution. Configuration files were previously generated manually using the agent, since the plugin's agent cannot be used at the moment due to a lack of integration tests.

To build the native image, run the following:

```sh
mvn -Pnative package
```

This will build an artifact under `cli/target/cli-1.1.0-SNAPSHOT`. You can then use it as you normally would zdb.

> Note, the binary is pretty big, but I guess that's life? It's 41M. I'm still not familiar enough with GraalVM's native image to know how to optimize binary size.

To generate the configuration files, you can simply run the `jar-with-dependencies` with the native image agent.

```sh
java -agentlib:native-image-agent=config-output-dir=./cli/src/main/resources/META-INF/native-image/io.zell.zdb.cli -jar cli/target/cli-1.1.0-SNAPSHOT-jar-with-dependencies.jar
```

To get a good configuration, especially for reflection, you'll want to run it with some different workloads. Note that right now, my PR contains the configuration files as formatted JSON since my IDE does this automatically. The agent will print out JSON with a different format, so you might see some changes, but they aren't really differences.

If there were tests, then the plugin can be configured to run the agent along the tests, and which should help provide some configuration. However, that configuration will also contain references to test libraries, so there's some manual effort involved to remove that.

Finally, you'll need to install GraalVM 22 compatible with Java 11. If you use sdkman, you can run:

```sh
sdk install java 22.0.0.2.r11-grl
```

I didn't dig into how to include this in releases (maybe JReleaser?) or the likes, or how to build for multiple architectures (i.e. a macOS build?), but I think it's a start :slightly_smiling_face:

### CODE REVIEW

**Comment by npepinpe** [comment]
OK, running the final build through [UPX](https://upx.github.io/), you can get the binary down to 14M, which is pretty nice. You can then build a Docker image from scratch as packaging :+1:

**Comment by Zelldon** [comment]
Awesome @npepinpe thanks for that! I think it will take some time for me to dig into this, but I think it is great. I was wondering that this works also with the state (read-only db) etc ? :thinking: So I have at the end a complete packaged native image I can run?

**Comment by npepinpe** [comment]
I generated the configuration with log use cases, so I imagine it's missing RocksDB stuff? It'd be mostly a case of running a couple times with the right workloads to map all the required reflection and JNI stuff. We can go through it together if you want.

**Comment by npepinpe** [comment]
We can take some time to look at it together. There's also easier ways to install GraalVM :smile:

**Comment by npepinpe** [comment]
It's missing the resource. This is why you want to run  with the agent with various workloads (or better, a complete suite of tests), so that you find all the reflection usage, all the resources it needs to package, all the classes that need to be loaded in non standard ways, etc. Otherwise you end up with missing things. Or you can hand write everything, but that's difficult except with very small projects.

**Comment by Zelldon** [comment]
Weird is that I tried all commands and combination with the agent and generated the resource configs :cry: but then after building it doesnt work :shrug: Idk have to check other day probably

**Comment by Zelldon** [comment]
@npepinpe would that also mean that it would fail again if a different process with different symbols is used, but was not part of the configuration ? Because that I think it is not really feasibel to use then

**Review by Zelldon — COMMENTED** [review]
Discussed today with @npepinpe. We should try to get the tests running with the plugin to generate the configs. This also means we need some tests for the cli module. It seems that some resources are missing (the bpm schema). The merge flag might not work as expected, Nicolas mention that he saw that this also removed/overwrites sometimes values.

**Pull request closed without merging**
